name: LearnActions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: step name
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: |
          echo print\(\'Learn actions\'\) > learn_actions.py
          python learn_actions.py        
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          echo "print('Learn actions')" > learn.py
          python learn.py
